#!/usr/bin/env bash

set -euo pipefail

command_roundtrip() {
    command_extract "$@"
    command_build "$@"
}

command_extract() {
    game=$1
    index=$(find_index "${game}")
    zig build run -- extract2 "src/fixtures/${game}/${index}" "/tmp/${game}"
}

command_build() {
    game=$1
    index=$(find_index "${game}")
    zig build run -- build2 "/tmp/${game}/project.scu" "/tmp/${game}build/${index}"
}

find_index() {
    game=$1
    find "src/fixtures/${game}" -iname '*.he0' -printf %P
}

"command_$@"
