#!/usr/bin/env bash

set -euo pipefail

command_roundtrip() {
    command_extract "$@"
    command_build "$1"
}

command_extract() {
    game=$1
    shift
    index=$(find_index "${game}")
    zig build run -- extract "src/fixtures/${game}/${index}" "/tmp/${game}" "$@"
}

command_build() {
    game=$1
    shift
    index=$(find_index "${game}")
    zig build run -- build "/tmp/${game}/project.scu" "/tmp/${game}build/${index}" "$@"
}

command_xor() {
    game=$1
    for file in "/tmp/${game}build"/*; do
        ext=${file##*.}
        [[ ${ext,,} =~ he0|he1|(a)|(b) ]] && key=69 || key=00
        <"src/fixtures/${game}/${file##*/}" xor -x "${key}" >"/tmp/f.${ext}"
        <"${file}" xor -x "${key}" >"/tmp/b.${ext}"
    done
}

find_index() {
    game=$1
    find "src/fixtures/${game}" -iname '*.he0' -printf %P
}

"command_$@"
